### PR TITLE
Added Income and Expenditure to Custom Data capture and removed Catering Income

### PR DESCRIPTION
**Pull request by WolfyUK**
### Context
[AB#216378](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/216378) [AB#198080](https://dfe-ssp.visualstudio.com/a14e55df-4fbf-4a2f-a11d-22b187178343/_workitems/edit/198080)

### Change proposed in this pull request
Added two fields and removed one from the first (financial) Custom Data capture form

### Checklist
- [x] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)
- [x] Your code builds clean without any errors or warnings
- [x] You have run all unit/integration tests and they pass
- [x] Your branch has been rebased onto main
- [x] You have tested by running locally

### CODE REVIEW

**Review by jrabbott — CHANGES_REQUESTED** [review]
These changes need to be reflected in `CustomDataPayload` in `PipelineMessage.cs`

**Comment by WolfyUK** [comment]
> These changes need to be reflected in `CustomDataPayload` in `PipelineMessage.cs`

This looks to already be the case. I verified the message being placed on the queue and in the respective tables.

**Comment by jrabbott** [comment]
@WolfyUK there is still the prop for catering income. If we've tested the end-2-end then this is having no impact, then all good.

image

**Review by jrabbott — APPROVED** [review]

**Comment by WolfyUK** [comment]
> @WolfyUK there is still the prop for catering income. If we've tested the end-2-end then this is having no impact, then all good.

Weird!

image

**Pull request merged**
