### PR TITLE
increased the default waiting time to 30secs

### PR DESCRIPTION
**Pull request by Faizi52996**
### Context
there are some flaky tests because of timeout. increased it to 30 secs now

### Change proposed in this pull request
n/a
### Guidance to review 
n/a
### Checklist
~~- [ ] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)~~
- [x] Your code builds clean without any errors or warnings
~~- [ ] You have run all unit/integration tests and they pass~~
- [x] Your branch has been rebased onto main
- [x] You have tested by running locally

### CODE REVIEW

**Review by jrabbott — COMMENTED** [review]
If pages/elements are taking longer than 30 secs, I think we need to review it.

**Comment by Faizi52996** [comment]
> If pages/elements are taking longer than 30 secs, I think we need to review it.

currently the default timeout is 5s but in our case sometime the chart takes more time to load causing flakiness. if they would take more than 30s(worst case) then definitely need to review them.

**Comment by jrabbott** [comment]
@Faizi52996 why are we only just seeing this?

**Comment by Faizi52996** [comment]
@jrabbott, the recent history pages changes seem to have affected more with this. Previously we made the use of ` await page.WaitForLoadStateAsync(LoadState.NetworkIdle);` in few places but now i think it would make sense to increase the waiting time rather than waiting for loadstate at different stages.

**Comment by Faizi52996** [comment]
@jrabbott , I see what you mean. This probably is not the root cause in this case. closing this PR for now for further troubleshooting.

**Pull request closed without merging**
